<?php
$AZURE_MYSQL_DBCONNECT_HOST = "gestordecitasdemo-server.mysql.database.azure.com";
$AZURE_MYSQL_DBCONNECT_USERNAME = "dptkvmzuil";
$AZURE_MYSQL_DBCONNECT_PASSWORD = "Z5UE64DVF78R082Y$";
$AZURE_MYSQL_DBCONNECT_DBNAME = "members";
$AZURE_MYSQL_DBCONNECT_PORT = "3306";
$AZURE_MYSQL_DBCONNECT_FLAG = "MYSQLI_CLIENT_SSL";

$conn = new mysqli($AZURE_MYSQL_DBCONNECT_HOST, $AZURE_MYSQL_DBCONNECT_USERNAME, $AZURE_MYSQL_DBCONNECT_PASSWORD, $AZURE_MYSQL_DBCONNECT_DBNAME, $AZURE_MYSQL_DBCONNECT_PORT, $AZURE_MYSQL_DBCONNECT_FLAG);
if (!$conn) {
   die('Database connection failed');
}
?>